branch-defaults:
  develop:
    environment: cb-dev-env
environment-defaults:
  cb-dev-env:
    branch: null
    repository: null
global:
  application_name: cyber-beanstalk
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Puma with Ruby 2.4
    running on 64bit Amazon Linux/2.6.1
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: cyber
  sc: git
  workspace_type: Application
